export const userTypes = {
    SET_CURRENT_USER_START: 'SET_CURRENT_USER_START',
    SET_CURRENT_USER_SUCCESS: 'SET_CURRENT_USER_SUCCESS',
    SET_CURRENT_USER_FAILURE: 'SET_CURRENT_USER_FAILURE',
    LOG_OUT_USER: 'LOG_OUT_USER'
}